### ISSUE TITLE
How to run 2 shared databases?

### ISSUE THREAD

**Issue by kenjibailly** [vrtmrz/livesync-classroom#2]
I've seen that the "Shared" And "Private" keys are set and cannot be changed, therefore I have no idea if one can be added.
I'm probably being a dick here being impatient for the wiki. I was just thinking that this might not be possible right now.

Sorry if I'm spamming you over here! 

```json
    "shared": {
        "uri": "",
        "auth": {
            "username": "",
            "password": "",
            "passphrase": ""
        },
        "path": "Collabs/"
    }
```

Would be nice if I could add another "shared" and another "private". This way there could be some kind of user database structure I could create.

Thanks again for the amazing changes right now, I'm loving it!

**Comment by vrtmrz** [comment]
I'm really sorry for naming the entries... I made an excuse.

> // "private" and "shared" don't mean which is primary or not.
> // They are even. But I made so many misconfigurations while debugging
> // with the names "database_a" and "database_b",
> // so it was just named as like this.

I thought, synchronize multiple vaults using multiple processes. 
But you're right. It usually is used with multiple pairs of vaults.
It should be the default feature. So I implemented.

**Comment by kenjibailly** [comment]
I didn't get any bugs when trying out the new version, believe me I tried :D
